auth:
  postgresPassword: admin

service:
  type: NodePort
  nodePorts:
    postgresql: 30007

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"

replicaCount: 1