name: Build and Test

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.3'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod download
        working-directory: app

      - name: Lint
        run: |
          go install golang.org/x/lint/golint@latest
          golint ./...
          go vet ./...
        working-directory: app

      - name: Run gosec (Security Scanner)
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          gosec ./...
        working-directory: app

      - name: Run tests with coverage
        run: |
          go test -v -coverprofile=coverage.out ./...
        working-directory: app

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.out
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Build
        run: go build -v ./...
        working-directory: app